name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-
    
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./out
        retention-days: 1

    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: distfiles



    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: distfiles/*
        target: "/home/${{ secrets.VPS_USERNAME }}/delete-after-use/www/"
        strip_components: 1
        timeout: 120s
        rm: true  # Supprime les fichiers existants
        overwrite: true